#!/bin/bash -e
# Oak D udev rules
if [ -f /etc/udev/rules.d/80-movidius.rules ]
then
echo "Udev rule already installed! Everything is fine :)"
else
echo 'SUBSYSTEM=="usb", ATTRS{idVendor}=="03e7", MODE="0666"' | tee /etc/udev/rules.d/80-movidius.rules
udevadm control --reload-rules && udevadm trigger
if [ -f /etc/udev/rules.d/80-movidius.rules ] 
then
echo "Udev rule correctly installed! Everything is fine :)"
else
echo "Something went wrong... :("
fi
fi

